### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by Ishannaik** [ckcr4lyf/deluge-dc-notif#4] opened 2021-02-09 05:30 UTC
```
sh: 1: deluge-console: not found
Traceback (most recent call last):
  File "delugePush.py", line 127, in <module>
    getState(torrentHash, torrentName, RATIO_CHECK_DELAY, False)
  File "delugePush.py", line 97, in getState
    if (lines[3].find('State: Downloading') == 0):
IndexEr: not foundndex out of range
```
When I try to run

**Comment by ckcr4lyf** [comment] 2021-02-13 04:45
You need to have the `deluge-console` binary to use this script.

**Comment by bobskiman** [comment] 2021-07-10 19:24
Hi, I can confirm a similar issue although not 100% the same, but it seems to affect the code. 
when doing a manual test via hash, i get 

```
# python3 delugePush.py ec14426efba962e29adeb462e3c82140d88c55ff
Traceback (most recent call last):
  File "delugePush.py", line 127, in <module>
    getState(torrentHash, torrentName, RATIO_CHECK_DELAY, False)
  File "delugePush.py", line 100, in getState
    ratioIndex = lines[5].find('Ratio: ')
IndexError: list index out of range
```

I can confirm that deluge-console is installed in my case, im using _linuxserver/deluge_ docker container.

**Comment by ckcr4lyf** [comment] 2023-02-18 04:36
Closing since no feedback.

**Closed by ckcr4lyf** 2023-02-18 04:36 UTC
